### ISSUE TITLE
Overthink Outputters

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#168]
We need to think again about the Outputter concept. I love the main idea but the devil's in the details. So here's our mantra:

# Outputters are modules that communicate with the user. Not more.

This is very important. We need to make sure that the outputter doesn't have to care about internal logics of coala. It should be easy to write an outputter.

Please note that Outputters should deal with input _and_ output. The name Outputter seems misleading to me, we should probably change that. Its more of an "Interactor".

Outputters have a well defined interface that defines how they get everything from and to coala. We currently have such an interface but it grew over time and we need to rethink it as a whole thing.

Outputters shall be flexible, take arbitrary settings and be easily configurable. See #166 about an approach to solve that.

# Flexibility

An outputter shall be highly flexible. What I mean with this: it shall allow the user to view arbitrary data and perform arbitrary actions on that data.

The Outputter has to implement the whole viewing functionality by itself. Thus it should probably have print methods for all kinds of results we support to be complete.

However it would be cool if the Outputter would provide some generic module slot that coala could fill by, lets name them "ActionProviders" for now. Those ActionProviders could provide actions that are applicable to a result. They should also provide a description of the action. Examples for those kinds of action could be:

 * Save this result to a log file
 * Apply patch/diff
 * Save this patch/diff to a .patch file
 * Save this patch as a git/svn/hg commit on the current repository

Those ActionProvider's could take arbitrary parameters just as Bears or Outputters take arbitrary settings and are creatable from a section. However those parameters shall not be saved to a section since they are to be applied to this one and only result.

### Why do we need to have YET ANOTHER modular component for coala? Couldn't coala provide those actions to the outputters via a simple interface?

I want the user to be able to perform whatever action he wants on his data. If he e.g. works in some weird company that uses some weird and inefficient version control system he might want to write an ActionProvider that does the equivalent of a git commit. Another reason is me loving modular design.

# TODO List

- [x] Find a new name for the Outputter
- [x] Fix #166 
- [x] Rethink Outputter interface (plus implementation)
- [x] Think of an ActionProvider interface (plus implementation)

# P.S.:

I'd love to hear any comments about this concept.

**Comment by Makman2** [comment]
Good thing if you want to redirect output (so not display it every time in the console). Seems to be a good concept for me (even as an outsider) :)

**Comment by sils1297** [comment]
The Outputter concept is already in place. Its just that we have only one outputter - the Console one. But you can see e.g. that we have a VoicePrinter that could be used to make a VoiceOutputter for blind users or so. We had this concept in mind right from the beginning. It will also allow us to write GUIs as Outputters.

**Comment by sils1297** [comment]
The RFC was for the ActionProvider things.

**Comment by sils1297** [comment]
first parts solved on #180

**Comment by sils1297** [comment]
ResultAction base class is on #185

**Comment by sils1297** [comment]
which is the ActionProvider but ResultAction doesn't sound so scaring IMO.

**Comment by sils1297** [comment]
OK: we need
- [ ] Some result actions
- [ ] Outputter support for result actions
- [ ] Results shall advertise what actions are applicable

**Comment by sils1297** [comment]
done on #195
