### ISSUE TITLE
Release 0.7/0.3

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#2115]
### For the coala-bears release, we should:
 - [ ] Go through all bears and document them properly, should be fairly easy.
 - [ ] Make a version of coala-html usable, CC @tushar-rishav ? Prototype is almost ready, right? https://github.com/coala-analyzer/coala-html/issues/43
 - [ ] Make more bears configurable [R](https://github.com/coala-analyzer/coala-bears/issues/376), [CheckStyle](https://github.com/coala-analyzer/coala-bears/issues/375), [ESLint](https://github.com/coala-analyzer/coala-bears/issues/374), [GNUIndent](https://github.com/coala-analyzer/coala-bears/issues/373), [RuboCop](https://github.com/coala-analyzer/coala-bears/issues/372) with the [tracking task](https://github.com/coala-analyzer/coala-bears/issues/340)
 - [ ] Make more PMD related bears for the other languages it supports as PMD is quite sophisticated
 - [ ] Make a few more sophisticated bears, looking into sophisticated analysis which is something people really want to see. (More towards security) https://github.com/coala-analyzer/coala-bears/issues/389 and https://github.com/coala-analyzer/coala-bears/issues/395
 
### For the coala part:
 - [x] caching, in the works and maturing so we can give the users the option and not enable it by default (next release after, phasing this in slowly) https://github.com/coala-analyzer/coala/issues/1991 https://github.com/coala-analyzer/coala/issues/18
 - [x] Diff renaming and deletion, PR in the works started from somebody and already a bit reworked by me https://github.com/coala-analyzer/coala/issues/1419
 - [x] Document linter https://github.com/coala-analyzer/coala/issues/2051

**Comment by sils1297** [comment]
Also https://github.com/coala-analyzer/docker-coala-base/issues should be solved. At least some so we get most stuff in the image.

**Comment by hypothesist** [comment]
> Go through all bears and document them properly, should be fairly easy.

solved with bear-docs? Or do we want something more comprehensive?

**Comment by sils1297** [comment]
Actually this one would be about adding CAN_FIX and CAN_DETECT attributes and improving the main description. Not all bears have a proper description yet.

**Comment by sils1297** [comment]
most stuff is there, the release happened - everyone's happy :)
