### ISSUE TITLE
Release: 0.8

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#2404]
Hey people, the following tasks are what I think super important for this release. Can you please push this :+1: reaction if you accept the responsibility? If you do that we expect you to reach your goal without us having to push you daily, if you need help just ask us, being annoying is fine. I'd love to see a relaase somewhere between 17-24 july when most of us are in spain.

- [x] @Udayan12167 get the cEP for next gen bears ready. Can we try to do quicker iterations here? Not doing for this release
- [x] @fneu can we get the docker container ready ASAP?
- [x] @Adrianzatreanu by any chance, can we have the single bear packages up within a month?
- [x] @Asnelchristian you have helped us a lot with adding new settings to bears. I would love to see https://github.com/coala-analyzer/coala-bears/issues/460 solved and if you'd be willing to drive that I'll be happy to provide any assistance you need for it. `Asnel said this around 75% complete; so I'm announcing this for the release`
- [x] @mr-karan you have some improvements for coala itself in your plan, will you manage to bring in a few of those soon?
- [x] @hypothesist can we get an initial version of coala-quickstart out of the door?
- [x] @hypothesist let's make caching default, shall we?
- [x] @arafsheikh I think it'd be sane to definitely do a coala eclipse release this time.
- [ ] @Redridge we should finish your language independent bear writing utilities from the coala side completely for this release. We should use the same JSON spec that we use for outputting results IMO.
- [ ] @Makman2 @AbdealiJK I think we should clean up the issues a bit, for sure there are old and stale ones.
- [ ] @SanketDG how's the doc stuff going along? Will we have something usable for this one? I think it would be sane to expect that. I'd agressively try to fill gaps in https://docs.google.com/spreadsheets/d/1bm63TQHndmGf3HQ33fp9UEmGKNYI7dTkjMyFIof2PqA/edit#gid=0 with it.
- [x] @abhsag24 can we get the IndentationBear into a usable state for some languages? I'd agressively try to fill gaps in https://docs.google.com/spreadsheets/d/1bm63TQHndmGf3HQ33fp9UEmGKNYI7dTkjMyFIof2PqA/edit#gid=0 with it.
- [x] @hypothesist @mr-karan @Adrianzatreanu remove your code clones for this release please. There must be something happening here.
- [x] [Long questions don't wrap correctly](https://github.com/coala-analyzer/coala/issues/2546)
- [x] ["Files that will be checked" debug message appears twice](https://github.com/coala-analyzer/coala/issues/2544)

**Comment by sils1297** [comment]
CC @seblat anything we should focus on for making GitMate rock in your opinion?

**Comment by Asnelchristian** [comment]
:+1

2016-06-29 7:25 GMT+01:00 Lasse Schuirmann <notifications@github.com>:

**Comment by hypothesist** [comment]
Writing down the release notes over here:

For this release, we have had 26 developers from around the world contributing over 80 commits in the last 5 weeks.

This release has seen several performance improvements, along with some documentation enhancements.

**Changelog**

* Caching is now default. This is a huge performance improvement for HDD users (we've seen a 2x improvement when coala is run on coala).

I'll keep editing this later.

**Comment by AbdealiJK** [comment]
Closing as it's done
